# Generated by Django 5.0.4 on 2024-04-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your Product Name', max_length=256)),
                ('price', models.FloatField(help_text='Product Price')),
                ('description', models.CharField(help_text='Your product description', max_length=1028)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product',
                'ordering': ['-created_at'],
            },
        ),
    ]
